### ISSUE TITLE
In polyabolos, add some hint for the special behavior of "single-abolo"

### ISSUE THREAD

**Issue by Shuenhoy** [AxelFox149/Polyform-Beta#2]
(By "single-abolo", I mean this gray abolo, if it has an official name, please tell me)
![image](https://github.com/AxelFox149/Polyform-Beta/assets/2196156/c9ea9ad3-3b17-4087-9de8-df4e59834f64)

I notice single-abolo has some special behaviors:
* Single-abolos always come with three pieces
* You cannot hold when the current piece is single-abolo
* The line clear will be pending until you get other type of polyabolo

I think this is designed to make special lines clear "triple" possible. However, this could be confusing for the new players, especially when they first reach M15 in Of Many Shapes. They may think there is a bug.

I suggest adding some hints, for example, putting a red cross mark on the hold cell, and changing the color of the pended line clears like the zone of TE:C.

Thanks!

**Comment by AxelFox149** [comment]
Yeah, I will add visual cues for polyabolos. There are still multiple improvements that I have to do with that piece set, and with that also including names for all pieces so don't worry, they don't have names yet
